#!/bin/bash

# Script written by Dr Eleni Christoforidou

# Define the output directory
OUTPUT_DIR="../FastQC output"

# Create the output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Loop through all .fastq.gz files in the current directory
for file in *.fastq.gz; do
    # Check if the file exists (to handle the case where no .fastq.gz files are found)
    if [ -e "$file" ]; then
        # Run FastQC on the file and output results to the specified directory
        fastqc "$file" -t 2 --nogroup --outdir="$OUTPUT_DIR"
        
        # Define the base name for the input file (removing .fastq.gz extension)
        base_name=$(basename "$file" .fastq.gz)
        
        # Define the expected name of the output zip file generated by FastQC
        zip_file="$OUTPUT_DIR/${base_name}_fastqc.zip"
        html_file="$OUTPUT_DIR/${base_name}_fastqc.html"

        # Define the new name for the fastqc_data.txt file
        txt_output_file="${base_name}_fastQC.txt"
        
        # Check if the zip file exists (to prevent errors)
        if [ -e "$zip_file" ]; then
            # Extract the fastqc_data.txt file from the zip file and rename it
            unzip -p "$zip_file" "${base_name}_fastqc/fastqc_data.txt" > "$OUTPUT_DIR/$txt_output_file"
        fi
        
        # Clean up: remove the other FastQC output files
        rm -f "$html_file"
        rm -f "$zip_file"
    fi
done

echo "FastQC processing complete. Output files saved in '$OUTPUT_DIR'."